spring:
  application:
    name: edge
    instance_id: ${myProcessId}
  cloud:
    consul:
        discovery:
           queryPassing: true             
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: httpd-httpd
          uri: lb://httpd-httpd
          predicates:
            - Path=/static/httpd/**
          filters:
            - RewritePath=/static/httpd/(?<remaining>.*), /$\{remaining}
        - id: restservice
          uri: lb://restservice
          predicates:
            - Path=/static/restservice/**
          filters:
            - RewritePath=/static/restservice/(?<remaining>.*), /$\{remaining}            
